<a href="https://colab.research.google.com/github/OliverGriffiths287/OliverGriffiths287.github.io/blob/main/python_code/Wages_scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
import re
import json
import pandas as pd

In [ ]:
from mmap import PAGESIZE
url = "https://www.planetfootball.com/quick-reads/premier-league-wages-increase-figures"

req = requests.get(url)
page_src = req.text

start_index = page_src.index('/><strong>')
page_src = page_src[start_index:]

page_src = page_src.split('Brighton')[0]


page_src

'/><strong>Manchester City\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa0146,875<br />\n2013-14 Wages: 77,784<br />\nWage Increase: 89%</p>\n<p><strong>Manchester United</strong></p>\n<p>2022-23 Wages: 133,448<br />\n2013-14 Wages:\xa050,568<br />\nWage Increase: 164%</p>\n<p><strong>Chelsea</strong></p>\n<p><meta />2022-23 Wages:\xa0124,242<br />\n2013-14 Wages:\xa040,393<br />\nWage Increase: 208%</p>\n<p><strong>Liverpool\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa0104,167<br />\n2013-14 Wages:\xa036,070<br />\nWage Increase: 189%</p>\n<p><strong>Arsenal\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa083,609<br />\n2013-14 Wages: 33,815<br />\nWage Increase:\xa0147%</p>\n<p><meta /><strong>Tottenham\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa080,385<br />\n2013-14 Wages:\xa024,039<br />\nWage Increase: 234%</p>\n<p><meta /><strong>Aston Villa\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa075,995<br />\n2013-14 Wages: 17,514<br />\nWage Increase: 334%</p>\n<p><strong>West Ham\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa068,182<br />\n2013-14 Wages: 20,200<br />\nWage Increase: 238%</p>\n<p><strong>Everton\xa0</strong></p>\n<p>2022-23 Wages: 61,440<br />\n2013-14 Wages: 29,033<br />\nWage Increase: 112%</p>\n<p><strong>Crystal Palace\xa0</strong></p>\n<p><meta />2022-23 Wages: 53,750<br />\n2013-14 Wages: 8281<br />\nWage Increase: 549%</p>\n<p><meta /><strong>Leicester City\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa052,778<br />\n2014-15 Wages: 17,369<br />\nWage Increase: 204%</p>\n<p><strong>Newcastle United\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa050,017<br />\n2013-14 Wages: 18,930<br />\nWage Increase: 164%</p>\n<p><meta /><strong>Fulham\xa0</strong></p>\n<p><meta />2022-23 Wages: 44,720<br />\n2013-14 Wages:<br />\nWage Increase: 235%</p>\n<p><meta /><strong>Leeds United\xa0</strong></p>\n<p><meta />2022-23 Wages: 40,417<br />\n2020-21 Wages: 21,930<br />\nWage Increase: 84%</p>\n<p><meta /><strong>Nottingham Forest\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa037,458<br />\n2013-14 Wages: N/A<br />\nWage Increase: N/A</p>\n<p><meta /><strong>Southampton\xa0</strong></p>\n<p><meta />2022-23 Wages: 36,433<br />\n2013-14 Wages: 15,276<br />\nWage Increase: 139%</p>\n<p><strong>Wolves</strong></p>\n<p><meta />2022-23 Wages: 30,621<br />\n2013-14 Wages: 19,375<br />\nWage Increase: 58%</p>\n<p><strong>Bournemouth\xa0</strong></p>\n<p><meta />2022-23 Wages: 29,889<br />\n2015-16 Wages: 10,866<br />\nWage Increase: 175%</p>\n<p><strong>'

In [ ]:
from os import name
# Find all team entries using regex
team_entries = re.findall(r'<strong>(.*?)</strong>', page_src)

cleaned_teams = [name.replace('\xa0', '') for name in team_entries]

teams = cleaned_teams[:9] + [cleaned_teams[11]]

teams

dfteams = pd.DataFrame(teams)
dfteams.rename(columns={0: 'team'}, inplace=True)
dfteams

                team
0    Manchester City
1  Manchester United
2            Chelsea
3          Liverpool
4            Arsenal
5          Tottenham
6        Aston Villa
7           West Ham
8            Everton
9   Newcastle United

In [ ]:
# For all 2013-14 wages
wages_14 = re.findall(r'2013-14 Wages: (.*?)<br', page_src)
wages_13 = re.findall(r'2013-14 Wages:\xa0(.*?)<br', page_src)

wages_14 = wages_14 + wages_13
wages_14

dfwages_14 = pd.DataFrame(wages_14)
dfwages_14
dfwages_14.rename(columns={0: 'wages'}, inplace=True)
dfwages_14['season'] = '2014'
dfwages_14.loc[dfwages_14['wages'] == '77,784', 'team'] = 'Manchester City'
dfwages_14.loc[dfwages_14['wages'] == '50,568', 'team'] = 'Manchester United'
dfwages_14.loc[dfwages_14['wages'] == '40,393', 'team'] = 'Chelsea'
dfwages_14.loc[dfwages_14['wages'] == '36,070', 'team'] = 'Liverpool'
dfwages_14.loc[dfwages_14['wages'] == '33,815', 'team'] = 'Arsenal'
dfwages_14.loc[dfwages_14['wages'] == '24,039', 'team'] = 'Tottenham'
dfwages_14.loc[dfwages_14['wages'] == '17,514', 'team'] = 'Aston Villa'
dfwages_14.loc[dfwages_14['wages'] == '20,200', 'team'] = 'West Ham'
dfwages_14.loc[dfwages_14['wages'] == '29,033', 'team'] = 'Everton'
dfwages_14.loc[dfwages_14['wages'] == '8281', 'team'] = 'Crystal Palace'
dfwages_14.loc[dfwages_14['wages'] == '18,930', 'team'] = 'Newcastle United'
dfwages_14['wages'] = pd.to_numeric(dfwages_14['wages'].str.replace(',', ''), errors='coerce')
dfwages_14.reset_index(drop=True, inplace=True)
dfwages_14.drop(dfwages_14[dfwages_14['team'].isnull()].index, inplace=True)
dfwages_14

      wages season               team
0   77784.0   2014    Manchester City
1   33815.0   2014            Arsenal
2   17514.0   2014        Aston Villa
3   20200.0   2014           West Ham
4   29033.0   2014            Everton
5    8281.0   2014     Crystal Palace
6   18930.0   2014   Newcastle United
10  50568.0   2014  Manchester United
11  40393.0   2014            Chelsea
12  36070.0   2014          Liverpool
13  24039.0   2014          Tottenham

In [ ]:
page_src

'/><strong>Manchester City\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa0146,875<br />\n2013-14 Wages: 77,784<br />\nWage Increase: 89%</p>\n<p><strong>Manchester United</strong></p>\n<p>2022-23 Wages: 133,448<br />\n2013-14 Wages:\xa050,568<br />\nWage Increase: 164%</p>\n<p><strong>Chelsea</strong></p>\n<p><meta />2022-23 Wages:\xa0124,242<br />\n2013-14 Wages:\xa040,393<br />\nWage Increase: 208%</p>\n<p><strong>Liverpool\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa0104,167<br />\n2013-14 Wages:\xa036,070<br />\nWage Increase: 189%</p>\n<p><strong>Arsenal\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa083,609<br />\n2013-14 Wages: 33,815<br />\nWage Increase:\xa0147%</p>\n<p><meta /><strong>Tottenham\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa080,385<br />\n2013-14 Wages:\xa024,039<br />\nWage Increase: 234%</p>\n<p><meta /><strong>Aston Villa\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa075,995<br />\n2013-14 Wages: 17,514<br />\nWage Increase: 334%</p>\n<p><strong>West Ham\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa068,182<br />\n2013-14 Wages: 20,200<br />\nWage Increase: 238%</p>\n<p><strong>Everton\xa0</strong></p>\n<p>2022-23 Wages: 61,440<br />\n2013-14 Wages: 29,033<br />\nWage Increase: 112%</p>\n<p><strong>Crystal Palace\xa0</strong></p>\n<p><meta />2022-23 Wages: 53,750<br />\n2013-14 Wages: 8281<br />\nWage Increase: 549%</p>\n<p><meta /><strong>Leicester City\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa052,778<br />\n2014-15 Wages: 17,369<br />\nWage Increase: 204%</p>\n<p><strong>Newcastle United\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa050,017<br />\n2013-14 Wages: 18,930<br />\nWage Increase: 164%</p>\n<p><meta /><strong>Fulham\xa0</strong></p>\n<p><meta />2022-23 Wages: 44,720<br />\n2013-14 Wages:<br />\nWage Increase: 235%</p>\n<p><meta /><strong>Leeds United\xa0</strong></p>\n<p><meta />2022-23 Wages: 40,417<br />\n2020-21 Wages: 21,930<br />\nWage Increase: 84%</p>\n<p><meta /><strong>Nottingham Forest\xa0</strong></p>\n<p><meta />2022-23 Wages:\xa037,458<br />\n2013-14 Wages: N/A<br />\nWage Increase: N/A</p>\n<p><meta /><strong>Southampton\xa0</strong></p>\n<p><meta />2022-23 Wages: 36,433<br />\n2013-14 Wages: 15,276<br />\nWage Increase: 139%</p>\n<p><strong>Wolves</strong></p>\n<p><meta />2022-23 Wages: 30,621<br />\n2013-14 Wages: 19,375<br />\nWage Increase: 58%</p>\n<p><strong>Bournemouth\xa0</strong></p>\n<p><meta />2022-23 Wages: 29,889<br />\n2015-16 Wages: 10,866<br />\nWage Increase: 175%</p>\n<p><strong>'

In [ ]:
wages_23 = re.findall(r'2022-23 Wages: (.*?)<br', page_src)
wages_22 = re.findall(r'2022-23 Wages:\xa0(.*?)<br', page_src)

wages_23 = wages_23 + wages_22

dfwages_23 = pd.DataFrame(wages_23)
dfwages_23
dfwages_23.rename(columns={0: 'wages'}, inplace=True)
dfwages_23['season'] = '2023'
dfwages_23.loc[dfwages_23['wages'] == '146,875', 'team'] = 'Manchester City'
dfwages_23.loc[dfwages_23['wages'] == '133,448', 'team'] = 'Manchester United'
dfwages_23.loc[dfwages_23['wages'] == '124,242', 'team'] = 'Chelsea'
dfwages_23.loc[dfwages_23['wages'] == '104,167', 'team'] = 'Liverpool'
dfwages_23.loc[dfwages_23['wages'] == '83,609', 'team'] = 'Arsenal'
dfwages_23.loc[dfwages_23['wages'] == '80,385', 'team'] = 'Tottenham'
dfwages_23.loc[dfwages_23['wages'] == '75,995', 'team'] = 'Aston Villa'
dfwages_23.loc[dfwages_23['wages'] == '68,182', 'team'] = 'West Ham'
dfwages_23.loc[dfwages_23['wages'] == '61,440', 'team'] = 'Everton'
dfwages_23.loc[dfwages_23['wages'] == '53,750', 'team'] = 'Crystal Palace'
dfwages_23.loc[dfwages_23['wages'] == '50,017', 'team'] = 'Newcastle United'
dfwages_23['wages'] = pd.to_numeric(dfwages_23['wages'].str.replace(',', ''), errors='coerce')
dfwages_23.reset_index(drop=True, inplace=True)
dfwages_23.drop(dfwages_23[dfwages_23['team'].isnull()].index, inplace=True)
dfwages_23

     wages season               team
0   133448   2023  Manchester United
1    61440   2023            Everton
2    53750   2023     Crystal Palace
8   146875   2023    Manchester City
9   124242   2023            Chelsea
10  104167   2023          Liverpool
11   83609   2023            Arsenal
12   80385   2023          Tottenham
13   75995   2023        Aston Villa
14   68182   2023           West Ham
16   50017   2023   Newcastle United

In [ ]:
dfwage_14_23 = pd.concat([dfwages_14, dfwages_23], ignore_index=True)
dfwage_14_23

dfwage_14_23.to_csv('wages_14_23.csv', index=False)